In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth', 50)

In [2]:
shows = pd.read_csv('TMDB_tv_dataset_v3.csv')
shows.head()

,id,name,number_of_seasons,number_of_episodes,original_language,vote_count,vote_average,overview,adult,backdrop_path,...,tagline,genres,created_by,languages,networks,origin_country,spoken_languages,production_companies,production_countries,episode_run_time
0,1399,Game of Thrones,8,73,en,21857,8.442,Seven noble families fight for control of the ...,False,/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg,...,Winter Is Coming,"Sci-Fi & Fantasy, Drama, Action & Adventure","David Benioff, D.B. Weiss",en,HBO,US,English,"Revolution Sun Studios, Television 360, Genera...","United Kingdom, United States of America",0
1,71446,Money Heist,3,41,es,17836,8.257,"To carry out the biggest heist in history, a m...",False,/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg,...,The perfect robbery.,"Crime, Drama",Álex Pina,es,"Netflix, Antena 3",ES,Español,Vancouver Media,Spain,70
2,66732,Stranger Things,4,34,en,16161,8.624,"When a young boy vanishes, a small town uncove...",False,/2MaumbgBlW1NoPo3ZJO38A6v7OS.jpg,...,Every ending has a beginning.,"Drama, Sci-Fi & Fantasy, Mystery","Matt Duffer, Ross Duffer",en,Netflix,US,English,"21 Laps Entertainment, Monkey Massacre Product...",United States of America,0
3,1402,The Walking Dead,11,177,en,15432,8.121,Sheriff's deputy Rick Grimes awakens from a co...,False,/x4salpjB11umlUOltfNvSSrjSXm.jpg,...,Fight the dead. Fear the living.,"Action & Adventure, Drama, Sci-Fi & Fantasy",Frank Darabont,en,AMC,US,English,"AMC Studios, Circle of Confusion, Valhalla Mot...",United States of America,42
4,63174,Lucifer,6,93,en,13870,8.486,"Bored and unhappy as the Lord of Hell, Lucifer...",False,/aDBRtunw49UF4XmqfyNuD9nlYIu.jpg,...,It's good to be bad.,"Crime, Sci-Fi & Fantasy",Tom Kapinos,en,"FOX, Netflix",US,English,"Warner Bros. Television, DC Entertainment, Jer...",United States of America,45

In [3]:
shows = shows[['id', 'name', 'overview', 'genres', 'poster_path', 'type', 'tagline', 'created_by', 'networks', 
               'number_of_seasons', 'number_of_episodes', 'vote_count', 'vote_average']]
shows.head()

,id,name,overview,genres,poster_path,type,tagline,created_by,networks,number_of_seasons,number_of_episodes,vote_count,vote_average
0,1399,Game of Thrones,Seven noble families fight for control of the ...,"Sci-Fi & Fantasy, Drama, Action & Adventure",/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg,Scripted,Winter Is Coming,"David Benioff, D.B. Weiss",HBO,8,73,21857,8.442
1,71446,Money Heist,"To carry out the biggest heist in history, a m...","Crime, Drama",/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg,Scripted,The perfect robbery.,Álex Pina,"Netflix, Antena 3",3,41,17836,8.257
2,66732,Stranger Things,"When a young boy vanishes, a small town uncove...","Drama, Sci-Fi & Fantasy, Mystery",/49WJfeN0moxb9IPfGn8AIqMGskD.jpg,Scripted,Every ending has a beginning.,"Matt Duffer, Ross Duffer",Netflix,4,34,16161,8.624
3,1402,The Walking Dead,Sheriff's deputy Rick Grimes awakens from a co...,"Action & Adventure, Drama, Sci-Fi & Fantasy",/n7PVu0hSz2sAsVekpOIoCnkWlbn.jpg,Scripted,Fight the dead. Fear the living.,Frank Darabont,AMC,11,177,15432,8.121
4,63174,Lucifer,"Bored and unhappy as the Lord of Hell, Lucifer...","Crime, Sci-Fi & Fantasy",/ekZobS8isE6mA53RAiGDG93hBxL.jpg,Scripted,It's good to be bad.,Tom Kapinos,"FOX, Netflix",6,93,13870,8.486

In [4]:
shows.duplicated().sum()

3526

In [5]:
shows.isnull().sum()

id                         0
name                       5
overview               75306
genres                 68926
poster_path            59902
type                       0
tagline               163309
created_by            132143
networks               71050
number_of_seasons          0
number_of_episodes         0
vote_count                 0
vote_average               0
dtype: int64

In [6]:
shows['type'].value_counts()

type
Scripted       129301
Documentary     13864
Miniseries      10810
Reality          9682
Talk Show        2997
Video            1379
News              606
Name: count, dtype: int64

In [7]:
shows[shows['overview'].isna()].head()

,id,name,overview,genres,poster_path,type,tagline,created_by,networks,number_of_seasons,number_of_episodes,vote_count,vote_average
245,71740,40 y 20,NaN,Comedy,/6a5tGXaGimIBWntQUKKWyZcyj68.jpg,Scripted,NaN,Gustavo Loza,Blim,10,124,1446,8.000
391,73481,Ecomoda,NaN,"Comedy, Drama",/yMwHYtRmbE91pFjorzgfgS6JpKn.jpg,Scripted,NaN,Fernando Gaitán,RCN,1,35,1014,7.838
441,81146,Rosario Tijeras,NaN,"Action & Adventure, Crime, Drama",/mLu1bUkUIuW1569Q40KEgUgMZpy.jpg,Scripted,NaN,NaN,RCN,1,60,913,7.284
489,98387,Rubi,NaN,Soap,/sVh19iLGwTXp9fhIbzV33U9pmbh.jpg,Scripted,NaN,"Yolanda Vargas Dulché, Leonardo Padrón",Univision,1,26,833,7.438
524,78722,A Family of Ten,NaN,Comedy,/q3QOiemypop4JQgTsZIJgfYEXjS.jpg,Scripted,NaN,"Jorge Ortiz de Pinedo, Pedro Ortiz de Pinedo",Las Estrellas,10,148,781,8.047

In [8]:
shows = shows.dropna(subset=['name', 'overview', 'genres', 'poster_path'])
shows = shows[shows['type'].isin(['Scripted', 'Documentary', 'Miniseries'])]
shows.drop_duplicates(inplace=True)
shows = shows.reset_index(drop=True)

shows.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47520 entries, 0 to 47519
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  47520 non-null  int64
 1   name                47520 non-null  object
 2   overview            47520 non-null  object
 3   genres              47520 non-null  object
 4   poster_path         47520 non-null  object
 5   type                47520 non-null  object
 6   tagline             4345 non-null   object
 7   created_by          19500 non-null  object
 8   networks            41226 non-null  object
 9   number_of_seasons   47520 non-null  int64
 10  number_of_episodes  47520 non-null  int64
 11  vote_count          47520 non-null  int64
 12  vote_average        47520 non-null  float64
dtypes: float64(1), int64(4), object(8)
memory usage: 4.7+ MB

In [9]:
shows['overview'] = shows['overview'].fillna('')
shows['tagline'] = shows['tagline'].fillna('')

shows['genres'] = shows['genres'].apply(
    lambda x: x.split(', ') if isinstance(x, str) and x.strip() else []
)

shows['type'] = shows['type'].apply(
    lambda x: x.split(', ') if isinstance(x, str) and x.strip() else []
)

shows['created_by'] = shows['created_by'].apply(
    lambda x: x.split(', ') if isinstance(x, str) and x.strip() else []
)

shows['networks'] = shows['networks'].apply(
    lambda x: x.split(', ') if isinstance(x, str) and x.strip() else []
)

shows.head()

,id,name,overview,genres,poster_path,type,tagline,created_by,networks,number_of_seasons,number_of_episodes,vote_count,vote_average
0,1399,Game of Thrones,Seven noble families fight for control of the ...,"[Sci-Fi & Fantasy, Drama, Action & Adventure]",/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg,[Scripted],Winter Is Coming,"[David Benioff, D.B. Weiss]",[HBO],8,73,21857,8.442
1,71446,Money Heist,"To carry out the biggest heist in history, a m...","[Crime, Drama]",/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg,[Scripted],The perfect robbery.,[Álex Pina],"[Netflix, Antena 3]",3,41,17836,8.257
2,66732,Stranger Things,"When a young boy vanishes, a small town uncove...","[Drama, Sci-Fi & Fantasy, Mystery]",/49WJfeN0moxb9IPfGn8AIqMGskD.jpg,[Scripted],Every ending has a beginning.,"[Matt Duffer, Ross Duffer]",[Netflix],4,34,16161,8.624
3,1402,The Walking Dead,Sheriff's deputy Rick Grimes awakens from a co...,"[Action & Adventure, Drama, Sci-Fi & Fantasy]",/n7PVu0hSz2sAsVekpOIoCnkWlbn.jpg,[Scripted],Fight the dead. Fear the living.,[Frank Darabont],[AMC],11,177,15432,8.121
4,63174,Lucifer,"Bored and unhappy as the Lord of Hell, Lucifer...","[Crime, Sci-Fi & Fantasy]",/ekZobS8isE6mA53RAiGDG93hBxL.jpg,[Scripted],It's good to be bad.,[Tom Kapinos],"[FOX, Netflix]",6,93,13870,8.486

In [10]:
shows['tags'] = (
    shows['name'] + ' ' + 
    shows['overview'] + ' ' + shows['tagline'] + ' ' + 
    (shows['genres'].apply(lambda x: ' '.join(x)) + ' ')*2 + 
    shows['type'].apply(lambda x: ' '.join(x)) + ' ' + 
    (shows['created_by'].apply(lambda x: ' '.join(x)) + ' ')*3 + 
    shows['networks'].apply(lambda x: ' '.join(x))
)

shows.head()

,id,name,overview,genres,poster_path,type,tagline,created_by,networks,number_of_seasons,number_of_episodes,vote_count,vote_average,tags
0,1399,Game of Thrones,Seven noble families fight for control of the ...,"[Sci-Fi & Fantasy, Drama, Action & Adventure]",/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg,[Scripted],Winter Is Coming,"[David Benioff, D.B. Weiss]",[HBO],8,73,21857,8.442,Game of Thrones Seven noble families fight for...
1,71446,Money Heist,"To carry out the biggest heist in history, a m...","[Crime, Drama]",/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg,[Scripted],The perfect robbery.,[Álex Pina],"[Netflix, Antena 3]",3,41,17836,8.257,Money Heist To carry out the biggest heist in ...
2,66732,Stranger Things,"When a young boy vanishes, a small town uncove...","[Drama, Sci-Fi & Fantasy, Mystery]",/49WJfeN0moxb9IPfGn8AIqMGskD.jpg,[Scripted],Every ending has a beginning.,"[Matt Duffer, Ross Duffer]",[Netflix],4,34,16161,8.624,"Stranger Things When a young boy vanishes, a s..."
3,1402,The Walking Dead,Sheriff's deputy Rick Grimes awakens from a co...,"[Action & Adventure, Drama, Sci-Fi & Fantasy]",/n7PVu0hSz2sAsVekpOIoCnkWlbn.jpg,[Scripted],Fight the dead. Fear the living.,[Frank Darabont],[AMC],11,177,15432,8.121,The Walking Dead Sheriff's deputy Rick Grimes ...
4,63174,Lucifer,"Bored and unhappy as the Lord of Hell, Lucifer...","[Crime, Sci-Fi & Fantasy]",/ekZobS8isE6mA53RAiGDG93hBxL.jpg,[Scripted],It's good to be bad.,[Tom Kapinos],"[FOX, Netflix]",6,93,13870,8.486,"Lucifer Bored and unhappy as the Lord of Hell,..."

In [11]:
shows['tags'][0]

"Game of Thrones Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond. Winter Is Coming Sci-Fi & Fantasy Drama Action & Adventure Sci-Fi & Fantasy Drama Action & Adventure Scripted David Benioff D.B. Weiss David Benioff D.B. Weiss David Benioff D.B. Weiss HBO"

In [12]:
import re
from bs4 import BeautifulSoup

In [13]:
# Remove url
shows['tags'] = shows['tags'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))

# Remove html tags
shows['tags'] = shows['tags'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())

In [14]:
shows.iloc[50]['tags']

"Suits While running from a drug deal gone bad, Mike Ross, a brilliant young college-dropout, slips into a job interview with one of New York City's best legal closers, Harvey Specter. Tired of cookie-cutter law school grads, Harvey takes a gamble by hiring Mike on the spot after he recognizes his raw talent and photographic memory. Two lawyers. One degree. Drama Drama Scripted Aaron Korsh Aaron Korsh Aaron Korsh USA Network"

In [15]:
!pip install --upgrade sentence-transformers transformers accelerate pyarrow langchain_groq langchain pydantic

Requirement already satisfied: sentence-transformers in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (5.4.1)
Requirement already satisfied: transformers in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (5.6.2)
Requirement already satisfied: accelerate in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (1.13.0)
Requirement already satisfied: pyarrow in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (24.0.0)
Requirement already satisfied: langchain_groq in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (1.1.2)
Requirement already satisfied: langchain in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (1.2.15)
Requirement already satisfied: pydantic in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (2.13.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from sentence-transformers) (1.12.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from sentence-transformers) (2.7.1)
Requirement already satisfied: numpy>=1.20.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from sentence-transformers) (1.7.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from transformers) (0.16.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from transformers) (0.5.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2023.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.9.0)
Requirement already satisfied: certifi in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: psutil in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from accelerate) (7.0.0)
Requirement already satisfied: groq<1.0.0,>=0.30.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langchain_groq) (0.33.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.8 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langchain_groq) (1.3.2)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from groq<1.0.0,>=0.30.0->langchain_groq) (1.9.0)
Requirement already satisfied: sniffio in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from groq<1.0.0,>=0.30.0->langchain_groq) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from pydantic) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from pydantic) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from pydantic) (0.4.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.10 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (0.0.12)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (0.4.42)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (8.5.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.8->langchain_groq) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (0.23.0)
Requirement already satisfied: langgraph<1.2.0,>=1.1.5 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langchain) (1.1.9)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langgraph<1.2.0,>=1.1.5->langchain) (3.0.0)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langgraph<1.2.0,>=1.1.5->langchain) (1.0.11)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langgraph<1.2.0,>=1.1.5->langchain) (0.3.13)
Requirement already satisfied: xxhash>=3.5.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langgraph<1.2.0,>=1.1.5->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.10.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain) (1.11.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (2.4.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: click>=8.0.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from typer->transformers) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from rich>=10.11.0->typer->transformers) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from rich>=10.11.0->typer->transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\onedrive\documents\code\24. langchain\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers) (0.1.2)

In [ ]:
'''from sentence_transformers import SentenceTransformer
import pickle

model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(shows['tags'].tolist(), show_progress_bar=True)

pickle.dump(embeddings, open('/kaggle/working/embeddings.pkl', 'wb'))
pickle.dump(model, open('/kaggle/working/model.pkl', 'wb'))'''

In [19]:
import os
import pickle
from dotenv import load_dotenv
load_dotenv()

embeddings_path = os.getenv("EMBEDDINGS_PATH")
model_path = os.getenv("MODEL_PATH")

with open(embeddings_path, "rb") as f:
    embeddings = pickle.load(f)

with open(model_path, "rb") as f:
    model = pickle.load(f)

In [18]:
from sklearn.metrics.pairwise import cosine_similarity
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field

# Define the Schema
class Explanation(BaseModel):
    explanation: str = Field(..., description="A reason for why a recommended show is a good match.")

parser = PydanticOutputParser(pydantic_object=Explanation)

os.environ['GROQ_API_KEY'] = os.getenv('GROQ_API_KEY')
model = ChatGroq(model="llama-3.3-70b-versatile")

# Explanation function
def get_explanation(target_row, rec_row):
    template = """
    You are a razor-sharp TV critic known for your witty, insightful observations, 
    and explaining why a fan of "{target_name}" would love "{rec_name}".
        
        ---
        METADATA FOR ANALYSIS:
        TARGET SHOW: {target_name}
        - Genres: {target_genres}
        - Creator/Team: {target_creator}
        - Synopsis: {target_overview}
        
        RECOMMENDED SHOW: {rec_name}
        - Genres: {rec_genres}
        - Creator/Team: {rec_creator}
        - Synopsis: {rec_overview}
        ---
        
        INSTRUCTIONS:
        1. IDENTIFY THE HOOK by looking for shared universes, shared creators, or strong thematic parallels.
        2. USE EXTERNAL LORE of these shows' plots, character arcs, and cultural impact.
        3. Be SPECIFIC about plot elements, character traits, or storytelling techniques
        4. Use ACTIVE, vivid language (not "this show has" or "features")
        5. NO generic phrases like "captivating storyline", "must-watch", "rollercoaster"
        6. NO starting with "Fans of X will enjoy..." or "If you liked X..."
        7. Be CONCISE and sound like a knowledgeable friend, not a marketing robot
        
        Write ONE sharp, specific explanation that makes me instantly want to watch {rec_name}.
        
        {format_instructions}
        
        JSON RESPONSE:"""
    
    prompts = PromptTemplate(
        input_variables=["target_name", "target_overview", "target_genres", "target_creator", "rec_name", "rec_overview", "rec_genres", 
                         "target_creator"],
        template=template,
        partial_variables={"format_instructions": parser.get_format_instructions()}
    )
    
    chain = prompts | model | parser
    
    response = chain.invoke({
        "target_name": target_row['name'],
        "target_overview": target_row['overview'],
        "target_genres": ', '.join(target_row['genres']),
        "target_creator": ', '.join(target_row['created_by']),
        "rec_name": rec_row['name'],
        "rec_overview": rec_row['overview'],
        "rec_genres": ', '.join(rec_row['genres']),
        "rec_creator": ', '.join(rec_row['created_by'])
    })
    
    return response.explanation

def recommend(show_name, vote_count=0, vote_average=0, seasons=10, episodes=100):
    match = shows[shows['name'].str.lower() == show_name.lower()]
    
    if match.empty:
        print("Show not found")
        return
    
    idx = match.index[0]
    target_row = shows.iloc[idx]
    target_embedding = embeddings[idx].reshape(1, -1)
    
    filtered_indices = shows[
        (shows['vote_count'] >= vote_count) & 
        (shows['vote_average'] >= vote_average) &
        (shows['number_of_seasons'] <= seasons) &
        (shows['number_of_episodes'] <= episodes) &
        (shows.index != idx)
    ].index
    
    filtered_embeddings = embeddings[filtered_indices]
    similarity_scores = cosine_similarity(target_embedding, filtered_embeddings)[0]
    
    results = sorted(zip(filtered_indices, similarity_scores), key=lambda x: x[1], reverse=True)[:5]
    
    print(f"Recommendations for '{show_name}':\n" + "-"*30)
    
    for i, (f_idx, score) in enumerate(results):
        rec_row = shows.iloc[f_idx] 
        print(f"{i+1}. {rec_row['name']} -> (Score: {score:.4f})")
        
        explanation = get_explanation(target_row, rec_row)
        print(f"    💡 Why: {explanation}\n")
        
recommend("Better Call Saul", vote_average=8)

Recommendations for 'Better Call Saul':
------------------------------
1. Breaking Bad -> (Score: 0.4763)
    💡 Why: Vince Gilligan's masterful storytelling weaves a darkly comedic and philosophical thread through both series, but Breaking Bad plunges you into the depths of Walter White's desperation, where the lines between right and wrong are constantly blurred, and the consequences of playing with fire are felt in every pulse-pounding moment, much like Jimmy McGill's own morally ambiguous journey in Better Call Saul.

2. Storm -> (Score: 0.3659)
    💡 Why: Storm's morally ambiguous landscape, where a respected detective compromises his integrity to save a loved one, echoes the transformation of Jimmy McGill into Saul Goodman, as both characters navigate the gray areas between right and wrong, raising questions about the true cost of desperation and the blurred lines between good and evil.

3. Harvey Birdman, Attorney at Law -> (Score: 0.3563)
    💡 Why: The morally ambiguous world of 'Better Call Saul' finds a surprisingly apt counterpart in 'Harvey Birdman, Attorney at Law', where the titular character's struggles to balance his heroic past with his newfound career as a lawyer mirror Jimmy McGill's own transformation into the morally dubious Saul Goodman, both characters walking a fine line between right and wrong, with Birdman's absurd, cartoonish cases serving as a clever commentary on the blurred lines between justice and chaos.

4. Doctor Lawyer -> (Score: 0.3533)
    💡 Why: In 'Doctor Lawyer', the razor-sharp mind of a genius surgeon turned lawyer slices through the complexities of medical crimes, echoing the calculating precision of Mike Ehrmantraut's 'fixer' mindset in 'Better Call Saul', as both characters navigate the dark underbelly of their respective professions with unflinching determination and a keen sense of justice.

5. Almost Perfect -> (Score: 0.3495)
    💡 Why: The morally ambiguous transformation of Jimmy McGill into Saul Goodman in Better Call Saul is mirrored in the fish-out-of-water story of an executive producer navigating the cutthroat world of television, where the lines between right and wrong are constantly blurred, much like the character's own romantic relationship with an assistant D.A., as seen in Almost Perfect, which shares a similar tone of witty banter and strong ensemble dynamics, making it a great match for those who enjoy the complex character development and dark humor found in Better Call Saul.